{% set name = "dedupe-hcluster" %}
{% set version = "0.3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dedupe-hcluster-{{ version }}.tar.gz
  sha256: 291e87ef7db4656d7365f7665e7a5e5b7ef9bc83bba49e6c33efe11d9a689dbf

build:
  number: 4
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - numpy
    - pip
    - python
  run:
    - numpy  # [py>38]
    - python

test:
  imports:
    - hcluster
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/datamade/hcluster
  summary: Hierarchical Clustering Algorithms (Information Theory)
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - osamples
    - izahn
